services:
  - type: web
    name: bupue-backend
    env: node
    plan: free
    buildCommand: cd bupue-backend && npm install
    startCommand: cd bupue-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
